# Generated by Django 3.1 on 2020-08-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('news', 'Новости'), ('economics', 'Экономика'), ('science', 'Наука'), ('tech', 'Техника'), ('it', 'IT'), ('none', 'Без категории'), ('sport', 'Спорт')], default='none', max_length=30)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.categories'),
        ),
    ]
